### ISSUE TITLE
Update to Manifest v3

### ISSUE THREAD

**Issue by Aleksandra0056** [tnychn/media-controller-extension#1]
Hello, I want to say, that the Manifest v2 is slowly being outdated, so it would be good if you update this extension to Manifest v3.

By the way, very nice extension!

**Comment by vlakoff** [comment]
Playing a bit with AI, I figured out the following changes to make (see also my additional notes at bottom):

1. **Background Scripts to Service Workers**:
    - **Change**: Replace the `background.scripts` key with `background.service_worker`.
    - **Reason**: Manifest V3 uses service workers for better performance and security, as they are event-driven and only run when needed.
    - **Example**:
      ```js
      // Before (V2)
      "background": {
        "scripts": ["background.js"]
      }
      // After (V3)
      "background": {
        "service_worker": "background.js"
      }
      ```

2. **Browser Action to Action**:
    - **Change**: Replace `browser_action` with `action`.
    - **Reason**: Manifest V3 consolidates user interface actions under `action`, streamlining the configuration.
    - **Example**:
      ```js
      // Before (V2)
      "browser_action": {
        "browser_style": true,
        "default_icon": {
          "128": "icon.light.svg"
        },
        "default_title": "Media Controller",
        "default_popup": "popup/index.html"
      }
      // After (V3)
      "action": {
        "default_icon": {
          "128": "icon.light.svg"
        },
        "default_title": "Media Controller",
        "default_popup": "popup/index.html"
      }
      ```

3. **Web Accessible Resources**:
    - **Change**: Update the syntax to specify resources and matching URL patterns.
    - **Reason**: Manifest V3 requires a more explicit definition for security and control.
    - **Example**:
      ```js
      // Before (V2)
      "web_accessible_resources": [
        "media.js"
      ]
      // After (V3)
      "web_accessible_resources": [{
        "resources": ["media.js"],
        "matches": ["<all_urls>"]
      }]
      ```

4. **Permissions**:
    - **Change**: Separate host permissions from other permissions.
    - **Reason**: Manifest V3 introduces `host_permissions` to clarify which URLs the extension can interact with.
    - **Example**:
      ```js
      // Before (V2)
      "permissions": [
        "tabs",
        "<all_urls>"
      ]
      // After (V3)
      "permissions": [
        "tabs",
        "activeTab"
      ],
      "host_permissions": [
        "<all_urls>"
      ]
      ```

5. **Removed `browser_style`**:
    - **Change**: Remove the `browser_style` property.
    - **Reason**: Manifest V3 does not support `browser_style`; use CSS for styling instead.
    - **Example**:
      ```js
      // Before (V2)
      "browser_action": {
        "browser_style": true,
        // other properties
      }
      // After (V3)
      "action": {
        // same properties minus browser_style
      }
      ```

----

Additional notes:
* Due to point 5 (which BTW is related to point 2), we no longer have the browser default styles, thus we might need to add some CSS.
* Notice in point 4 that we also have to add the `activeTab` permission:

  > In Manifest V2, the "tabs" permission was used to access the user's open tabs and interact with them. In Manifest V3, the "activeTab" permission is required to get access to the content of the currently active tab when the user interacts with the extension (e.g., by clicking on the extension icon). This change is part of a broader move towards more granular permissions to improve user privacy and security.

**Comment by vlakoff** [comment]
I'm not sure that these changes to the maniphest file would be sufficient.

In particular, see [Migrate to a service worker](https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers).

**Comment by vlakoff** [comment]
And discussing with the AI about the `background.js` that has to be converted to a service worker, I'm getting the following:

1. **Initialization and Storage:** 
   - Replaced `window.__tabs__` with `let tabs`, since `window` is not available in a service worker context.

2. **Executing Scripts:**
   - Updated `browser.tabs.executeScript` to `chrome.scripting.executeScript`, which is the new method for executing scripts in tabs in Manifest V3.

3. **OffscreenCanvas:**
   - Used `OffscreenCanvas` instead of creating a traditional canvas element, which is more suitable for background processes in a service worker.

  ```js
  const color = await (async (src) => {
    const canvas = new OffscreenCanvas(1, 1);
    const context = canvas.getContext("2d");
    return new Promise((resolve) => {
      const image = new Image();
      image.onload = () => {
        context.drawImage(image, 0, 0, 1, 1);
        resolve(context.getImageData(0, 0, 1, 1).data);
      };
      image.src = src;
    });
  })(thumbnail || tab.favIconUrl);
```

4. **Permissions and Context:**
   - Confirmed that the necessary permissions (`tabs`, `scripting`, etc.) should be specified in the manifest file.
   - Ensured compatibility with the service worker context, replacing `window` references where necessary.

5. **Miscellaneous Adjustments:**
   - Changed `browser` API to `chrome` API in most instances since `chrome` is the standard for Manifest V3.
   - Modified how badge text and color are set using `chrome.action` instead of `browser.browserAction`.

Here’s a specific example for clarity:

**Original code:**
```js
return (
  await browser.tabs.executeScript(tab.id, {
    code: `document.querySelector("meta[property='og:image']")?.getAttribute("content");`,
  })
)[0];
```

**Updated code:**
```js
return (
  await chrome.scripting.executeScript({
    target: { tabId: tab.id },
    func: () => document.querySelector("meta[property='og:image']")?.getAttribute("content"),
  })
)[0].result;
```

**Comment by tnychn** [comment]
Since this is a Firefox-specific extension and Mozilla has no [plans](https://blog.mozilla.org/addons/2024/03/13/manifest-v3-manifest-v2-march-2024-update/) to deprecate Manifest V2, I think sticking to MV2 for now would be better as the migration will probably break the extension's mechanism.
